version: '2'
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq:rabbit1 
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq 
    links:
      - rabbitmq:rabbit1
  rabbitmq:
    restart: always
    image: rabbitmq:latest
    hostname: "rabbit1"
    ports:
      - "5672:5672"
      - "15672:15672"


