version: '2'
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: /usr/bin/supervisord 
    image: flaskrq
    restart: always
    ports:
     - "80:80"
     - "443:443"
    depends_on:
      - redis
    links:
      - redis:redis1 
  worker:
    image: flaskrq
    command: python worker.py
    depends_on:
      - redis 
    links:
      - redis:redis1
  redis:
    restart: always
    image: redis:latest
    hostname: "redis1"

