version: '2'
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python app.py 
    image: flaskrq
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis
    links:
      - redis:redis1 
  worker:
    image: flaskrq
    command: python worker.py
    depends_on:
      - redis 
    links:
      - redis:redis1
  redis:
    restart: always
    image: redis:latest
    hostname: "redis1"

